# Generated by Django 6.0.7 on 2026-08-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispached", "Dispatched"),
                    ("denied", "Denied"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
